generic_sso.settings:
  type: config_object
  mapping:
    seamlessLogin:
      type: boolean
    ssoSplitUserRealm:
      type: boolean
    cookieExpire:
      type: boolean
    ssoVariable:
      type: string
    ssoExcludedPaths:
      type: sequence
      sequence:
        type: string
    ssoExcludedHosts:
      type: sequence
      sequence:
        type: string
    redirectOnLogout:
      type: boolean
    logoutRedirectPath:
      type: string
    enableLoginConfirmationMessage:
      type: boolean
    autoCreateUser:
      type: boolean
